export const markets = {
  ba: {
    lang: "bs",
    locale: "Bosna i Hercegovina",
    flag: "🇧🇦",
    switchTo: { href: "/rs.html", label: "Srbija 🇷🇸" },
    nav: ["Bundlovi", "Kako radi", "Pilot", "Kontakt"],
    badge: "AI Agenti · BiH",
    title: ["AI agenti koji rade", "umjesto vas."],
    titleAccent: "umjesto vas.",
    sub: "Izaberite paket agenata koji odgovara vašem biznisu. Poruke, termini, marketing, istraživanje — na autopilotu, od 25 EUR mjesečno.",
    cta: "Zatraži demo",
    ctaSub: "Pogledaj bundlove",

    bundles: [
      {
        icon: "🤖",
        name: "Solo Agent",
        price: "25",
        period: "EUR / mj.",
        tag: "Starter",
        target: "Freelanceri, mali biznisi",
        desc: "Jedan specijalizovani agent po vašem izboru — FAQ, prijem upita, termini ili pretraga dokumenata.",
        agents: ["1 agent (izaberite ulogu)", "2 kanala po izboru"],
        channels: "Viber · Messenger · WhatsApp",
      },
      {
        icon: "📚",
        name: "Learning Buddy",
        price: "29",
        period: "EUR / mj.",
        tag: "Edukacija",
        target: "Đaci 6–18 god. + roditelji",
        desc: "Personalizovani tutor koji objašnjava gradivo, pravi kvizove, prati napredak i šalje izvještaje roditeljima.",
        agents: ["Objašnjenje Agent", "Kviz Agent", "Lernplan Agent", "Roditelj Agent"],
        channels: "WhatsApp · Viber · Telegram",
      },
      {
        icon: "📱",
        name: "Social Marketing Team",
        price: "39",
        period: "EUR / mj.",
        tag: "Popularan",
        featured: true,
        target: "Saloni, restorani, butici, kafići",
        desc: "Kompletni marketing tim: kreira postove, planira objave, odgovara na poruke i vodi Facebook oglase.",
        agents: ["Content Agent", "Scheduling Agent", "Community Agent", "Ads Agent"],
        channels: "Facebook · Instagram · Viber",
      },
      {
        icon: "🔬",
        name: "Research Bundle",
        price: "49",
        period: "EUR / mj.",
        tag: "Akademski",
        target: "Studenti, istraživači, NGO",
        desc: "Akademski asistent: pretražuje dokumente, sažima tekstove, formatira citate i pravi planove učenja.",
        agents: ["Research Agent", "Summary Agent", "Citation Agent", "Study Planner"],
        channels: "Telegram · WhatsApp · Web",
      },
      {
        icon: "🏢",
        name: "Office Bundle",
        price: "79",
        period: "EUR / mj.",
        tag: "Profesionalan",
        target: "Advokati, doktori, arhitekti, agencije",
        desc: "Kompletna kancelarijska asistencija: termini, pozivi, email i dokumenti — sve automatizirano.",
        agents: ["Termin Agent", "Telefon Agent", "Mail Agent", "Dokument Agent"],
        channels: "Viber · WhatsApp · Email · Web",
      },
    ],

    steps: [
      {
        num: "01",
        title: "Izaberite bundle",
        desc: "Odaberite paket koji odgovara vašem poslu. Ne trebate IT tim.",
      },
      {
        num: "02",
        title: "Setup za 3–5 dana",
        desc: "Konfigurišemo agente na vašim kanalima. Vi samo potvrdite.",
      },
      {
        num: "03",
        title: "14 dana pilot",
        desc: "Pratimo, podešavamo, optimizujemo. Ne plaćate dok ne vidite rezultat.",
      },
    ],

    pilotTitle: "Tražimo pilot-klijente.",
    pilotDesc: "Ograničen broj mjesta. Postavljamo uz vas, ne umjesto vas.",
    pilotItems: ["14 dana iteracije", "Bez uplate unaprijed", "Jasan scope", "Povoljniji ulaz uz feedback"],

    faq: [
      ["Da li radi na bosanskom?", "Da. Svi agenti komuniciraju na BKS jeziku sa lokalnim formulacijama."],
      ["Koliko brzo se pokrene?", "3–5 dana od dogovora do živog agenta na vašim kanalima."],
      ["Mogu li kombinovati bundlove?", "Da. Svaki bundle radi nezavisno — možete koristiti više odjednom."],
      ["Kako se plaća?", "Mjesečna faktura, bez skrivenih troškova. Godišnji plan: 10 mjeseci plaćate, 12 koristite."],
    ],

    contactBlurb: "Pošaljite osnovne podatke i javimo se sa kratkom procjenom da li je pilot fit.",
    nextSteps: [
      "Kratka procjena (fit ili ne)",
      "Prijedlog bundle-a bez pritiska",
      "Jasan sljedeći korak",
    ],
    footerNote: "OpenClaw Balkan · BiH · AI agenti za lokalne firme",
  },

  rs: {
    lang: "sr",
    locale: "Srbija",
    flag: "🇷🇸",
    switchTo: { href: "/ba.html", label: "BiH 🇧🇦" },
    nav: ["Bundlovi", "Kako radi", "Pilot", "Kontakt"],
    badge: "AI Agenti · Srbija",
    title: ["AI agenti koji rade", "umesto vas."],
    titleAccent: "umesto vas.",
    sub: "Izaberite paket agenata koji odgovara vašem biznisu. Poruke, termini, marketing, istraživanje — na autopilotu, od 25 EUR mesečno.",
    cta: "Zatraži demo",
    ctaSub: "Pogledaj bundlove",

    bundles: [
      {
        icon: "🤖",
        name: "Solo Agent",
        price: "25",
        period: "EUR / mes.",
        tag: "Starter",
        target: "Freelanceri, mali biznisi",
        desc: "Jedan specijalizovani agent po vašem izboru — FAQ, prijem upita, termini ili pretraga dokumenata.",
        agents: ["1 agent (izaberite ulogu)", "2 kanala po izboru"],
        channels: "Viber · Messenger · WhatsApp",
      },
      {
        icon: "📚",
        name: "Learning Buddy",
        price: "29",
        period: "EUR / mes.",
        tag: "Edukacija",
        target: "Đaci 6–18 god. + roditelji",
        desc: "Personalizovani tutor koji objašnjava gradivo, pravi kvizove, prati napredak i šalje izveštaje roditeljima.",
        agents: ["Objašnjenje Agent", "Kviz Agent", "Lernplan Agent", "Roditelj Agent"],
        channels: "WhatsApp · Viber · Telegram",
      },
      {
        icon: "📱",
        name: "Social Marketing Team",
        price: "39",
        period: "EUR / mes.",
        tag: "Popularan",
        featured: true,
        target: "Saloni, restorani, butici, kafići",
        desc: "Kompletni marketing tim: kreira postove, planira objave, odgovara na poruke i vodi Facebook oglase.",
        agents: ["Content Agent", "Scheduling Agent", "Community Agent", "Ads Agent"],
        channels: "Facebook · Instagram · Viber",
      },
      {
        icon: "🔬",
        name: "Research Bundle",
        price: "49",
        period: "EUR / mes.",
        tag: "Akademski",
        target: "Studenti, istraživači, NGO",
        desc: "Akademski asistent: pretražuje dokumente, sažima tekstove, formatira citate i pravi planove učenja.",
        agents: ["Research Agent", "Summary Agent", "Citation Agent", "Study Planner"],
        channels: "Telegram · WhatsApp · Web",
      },
      {
        icon: "🏢",
        name: "Office Bundle",
        price: "79",
        period: "EUR / mes.",
        tag: "Profesionalan",
        target: "Advokati, doktori, arhitekti, agencije",
        desc: "Kompletna kancelarijska asistencija: termini, pozivi, email i dokumenti — sve automatizovano.",
        agents: ["Termin Agent", "Telefon Agent", "Mail Agent", "Dokument Agent"],
        channels: "Viber · WhatsApp · Email · Web",
      },
    ],

    steps: [
      {
        num: "01",
        title: "Izaberite bundle",
        desc: "Odaberite paket koji odgovara vašem poslu. Ne trebate IT tim.",
      },
      {
        num: "02",
        title: "Setup za 3–5 dana",
        desc: "Konfigurišemo agente na vašim kanalima. Vi samo potvrdite.",
      },
      {
        num: "03",
        title: "14 dana pilot",
        desc: "Pratimo, podešavamo, optimizujemo. Ne plaćate dok ne vidite rezultat.",
      },
    ],

    pilotTitle: "Tražimo pilot-klijente.",
    pilotDesc: "Ograničen broj mesta. Postavljamo uz vas, ne umesto vas.",
    pilotItems: ["14 dana iteracije", "Bez uplate unapred", "Jasan scope", "Povoljniji ulaz uz feedback"],

    faq: [
      ["Da li radi na srpskom?", "Da. Svi agenti komuniciraju na srpskom sa lokalnim formulacijama."],
      ["Koliko brzo se pokrene?", "3–5 dana od dogovora do živog agenta na vašim kanalima."],
      ["Mogu li kombinovati bundlove?", "Da. Svaki bundle radi nezavisno — možete koristiti više odjednom."],
      ["Kako se plaća?", "Mesečna faktura, bez skrivenih troškova. Godišnji plan: 10 meseci plaćate, 12 koristite."],
    ],

    contactBlurb: "Pošaljite osnovne podatke i javimo se sa kratkom procenom da li je pilot fit.",
    nextSteps: [
      "Kratka procena (fit ili ne)",
      "Predlog bundle-a bez pritiska",
      "Jasan sledeći korak",
    ],
    footerNote: "OpenClaw Balkan · Srbija · AI agenti za lokalne firme",
  },
};
